/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oieee;

import javax.swing.JOptionPane;
import static oieee.frmfacil.pontos;
import static oieee.frmfacil.sinalizador1;
import static oieee.frmfacil.sinalizador2;
import static oieee.frmfacil.sinalizador3;
import static oieee.frmfacil2.sinalizador4;
import static oieee.frmfacil2.sinalizador5;
import static oieee.frmfacil2.sinalizador6;
import static oieee.frmfacilfinal.sinalizador7;
import static oieee.frmfacilfinal.sinalizador8;
import static oieee.frmfacilfinal.sinalizador9;
import static oieee.frmfacilfinal.sinalizador10;
import static oieee.frmmedio1.sm1;
import static oieee.frmmedio1.sm2;
import static oieee.frmmedio2.sm3;
import static oieee.frmmedio2.sm4;
import static oieee.frmmedio3.sm5;
import static oieee.frmmedio3.sm6;
import static oieee.frmmedio3.sm7;
import static oieee.frmmedio4.sn8;
import static oieee.frmmedio4.sn9;
import static oieee.frmmedio4.sn10;
import static oieee.frmdificil.sd1;
import static oieee.frmdificil.sd2;
import static oieee.dificil2.sd3;
import static oieee.dificil2.sd4;
import static oieee.dificil2.sd5;
import static oieee.frmdificil3.sd6;
import static oieee.frmdificil3.sd7;
import static oieee.frmdificil3.sd8;
import static oieee.frmdificil4.sd9;
import static oieee.frmdificil4.sd10;
import static oieee.frmdificil5.sd11;
import static oieee.frmdificil5.sd12;




public class frmmenu extends javax.swing.JFrame {

 musica m = new musica();
 
 
    public frmmenu() {
        initComponents();
        m.playSound("mkwav.wav");
        pontuacao();
        classificacao();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(628, 254));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pontuação: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 70, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dificil.jpg"))); // NOI18N
        jButton1.setText("Dificil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 70, 120, 75);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nivel meme: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 180, 80, 14);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/facil.jpg"))); // NOI18N
        jButton3.setText("Fácil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 70, 120, 75);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medio1.jpg"))); // NOI18N
        jButton4.setText("Médio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 70, 120, 75);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 30, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 180, 210, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tk.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 250);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Opções");

        jMenuItem1.setText("Resetar jogo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this," Você escolheu o modo fácil!\n Cada questão correta valerá 10 pontos e caso erre não será descontado!\n Não há tempo para responder :).", "Informativo", JOptionPane.INFORMATION_MESSAGE);
        frmfacil f = new frmfacil();
        f.setVisible(true);
        this.dispose();
        m.stop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this," Você escolheu o modo médio!\n Cada questão correta valerá 10 pontos e caso erre será descontado 5 pontos!\n Não há tempo para responder :).\nObs: Cuidado com o Pivete!", "Informativo", JOptionPane.INFORMATION_MESSAGE);
        frmmedio1 medio = new frmmedio1();
        medio.setVisible(true);
        this.dispose();
        m.stop();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        sinalizador1 = 0;
        sinalizador2 = 0;
        sinalizador3 = 0;
        sinalizador4 = 0;
        sinalizador5 = 0;
        sinalizador6 = 0;
        sinalizador7 = 0;
        sinalizador8 = 0;
        sinalizador9 = 0;
        sinalizador10 = 0;
        sm1 = 0;
        sm2 = 0;
        sm3 = 0;
        sm4 = 0;
        sm5 = 0;
        sm6 = 0;
        sm7 = 0;
        sn8 = 0;
        sn9 = 0;
        sn10 = 0;
        sd1 = 0;
        sd2 = 0;
        sd3 = 0;
        sd4 = 0;
        sd5 = 0;
        sd6 = 0;
        sd7 = 0;
        sd8 = 0;
        sd9 = 0;
        sd10 = 0;
        sd11 = 0;
        sd12 = 0;
        
        
        pontos = 0;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this," Você escolheu o modo DIFICIL!\n Cada questão correta valerá 15 pontos e caso erre será descontado 5 pontos!\n Se você errar não poderá responder de novo.\n Você tem 20 segundos para responder cada questão!\nObs: Cuidado com o Pivete!", "Informativo", JOptionPane.INFORMATION_MESSAGE);
        frmdificil dificil = new frmdificil();
        dificil.setVisible(true);
        this.dispose();
        m.stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    void setSegundos(long microsecondPosition) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void pontuacao() {
        jLabel2.setText(Integer.toString(pontos));
    }

    private void classificacao() {
        if(pontos == 0)
        {
            jLabel4.setText("Você é nada!");
        }
        else if(pontos<=100)
        {
            jLabel4.setText("Você é um Meme Noob!");
        }
        else if(pontos > 100 && pontos <= 180)
        {
            jLabel4.setText("Você é um Meme Normal");
        }
        else if(pontos > 180 && pontos < 320)
        {
            jLabel4.setText("Você é um Meme Expert!");
        }
        else if(pontos == 320)
        {
            jLabel4.setText("Você é um MEME MASTER!");
        }
    }
}
